//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bloodpressure_tracking.user_Data {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfUserData", Namespace="http://tempuri.org/", ItemName="userData")]
    [System.SerializableAttribute()]
    public class ArrayOfUserData : System.Collections.Generic.List<bloodpressure_tracking.user_Data.userData> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="userData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class userData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        private int ageField;
        
        private char genderField;
        
        private float weightField;
        
        private float heightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int age {
            get {
                return this.ageField;
            }
            set {
                if ((this.ageField.Equals(value) != true)) {
                    this.ageField = value;
                    this.RaisePropertyChanged("age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public char gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float weight {
            get {
                return this.weightField;
            }
            set {
                if ((this.weightField.Equals(value) != true)) {
                    this.weightField = value;
                    this.RaisePropertyChanged("weight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float height {
            get {
                return this.heightField;
            }
            set {
                if ((this.heightField.Equals(value) != true)) {
                    this.heightField = value;
                    this.RaisePropertyChanged("height");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="user_Data.userSoap")]
    public interface userSoap {
        
        // CODEGEN: Generating message contract since element name fname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        bloodpressure_tracking.user_Data.RegisterResponse Register(bloodpressure_tracking.user_Data.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.RegisterResponse> RegisterAsync(bloodpressure_tracking.user_Data.RegisterRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_info", ReplyAction="*")]
        bloodpressure_tracking.user_Data.get_infoResponse get_info(bloodpressure_tracking.user_Data.get_infoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_info", ReplyAction="*")]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.get_infoResponse> get_infoAsync(bloodpressure_tracking.user_Data.get_infoRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update", ReplyAction="*")]
        bloodpressure_tracking.user_Data.updateResponse update(bloodpressure_tracking.user_Data.updateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/update", ReplyAction="*")]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.updateResponse> updateAsync(bloodpressure_tracking.user_Data.updateRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_readings", ReplyAction="*")]
        bloodpressure_tracking.user_Data.delete_readingsResponse delete_readings(bloodpressure_tracking.user_Data.delete_readingsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_readings", ReplyAction="*")]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.delete_readingsResponse> delete_readingsAsync(bloodpressure_tracking.user_Data.delete_readingsRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_user", ReplyAction="*")]
        bloodpressure_tracking.user_Data.delete_userResponse delete_user(bloodpressure_tracking.user_Data.delete_userRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/delete_user", ReplyAction="*")]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.delete_userResponse> delete_userAsync(bloodpressure_tracking.user_Data.delete_userRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_id", ReplyAction="*")]
        bloodpressure_tracking.user_Data.get_idResponse get_id(bloodpressure_tracking.user_Data.get_idRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/get_id", ReplyAction="*")]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.get_idResponse> get_idAsync(bloodpressure_tracking.user_Data.get_idRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        bloodpressure_tracking.user_Data.loginResponse login(bloodpressure_tracking.user_Data.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.loginResponse> loginAsync(bloodpressure_tracking.user_Data.loginRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoringPressure", ReplyAction="*")]
        bloodpressure_tracking.user_Data.StoringPressureResponse StoringPressure(bloodpressure_tracking.user_Data.StoringPressureRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/StoringPressure", ReplyAction="*")]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.StoringPressureResponse> StoringPressureAsync(bloodpressure_tracking.user_Data.StoringPressureRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(bloodpressure_tracking.user_Data.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public char gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public float w;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float h;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string password;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string fname, int age, char gender, float w, float h, string email, string password) {
            this.fname = fname;
            this.age = age;
            this.gender = gender;
            this.w = w;
            this.h = h;
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(bloodpressure_tracking.user_Data.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(int RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_infoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_info", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.get_infoRequestBody Body;
        
        public get_infoRequest() {
        }
        
        public get_infoRequest(bloodpressure_tracking.user_Data.get_infoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_infoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public get_infoRequestBody() {
        }
        
        public get_infoRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_infoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_infoResponse", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.get_infoResponseBody Body;
        
        public get_infoResponse() {
        }
        
        public get_infoResponse(bloodpressure_tracking.user_Data.get_infoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_infoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public bloodpressure_tracking.user_Data.ArrayOfUserData get_infoResult;
        
        public get_infoResponseBody() {
        }
        
        public get_infoResponseBody(bloodpressure_tracking.user_Data.ArrayOfUserData get_infoResult) {
            this.get_infoResult = get_infoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="update", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.updateRequestBody Body;
        
        public updateRequest() {
        }
        
        public updateRequest(bloodpressure_tracking.user_Data.updateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fname;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int age;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public char gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public float w;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public float h;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string password;
        
        public updateRequestBody() {
        }
        
        public updateRequestBody(string email, string fname, int age, char gender, float w, float h, string password) {
            this.email = email;
            this.fname = fname;
            this.age = age;
            this.gender = gender;
            this.w = w;
            this.h = h;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateResponse", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.updateResponseBody Body;
        
        public updateResponse() {
        }
        
        public updateResponse(bloodpressure_tracking.user_Data.updateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateResponseBody {
        
        public updateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delete_readingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete_readings", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.delete_readingsRequestBody Body;
        
        public delete_readingsRequest() {
        }
        
        public delete_readingsRequest(bloodpressure_tracking.user_Data.delete_readingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class delete_readingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public delete_readingsRequestBody() {
        }
        
        public delete_readingsRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delete_readingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete_readingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.delete_readingsResponseBody Body;
        
        public delete_readingsResponse() {
        }
        
        public delete_readingsResponse(bloodpressure_tracking.user_Data.delete_readingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class delete_readingsResponseBody {
        
        public delete_readingsResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delete_userRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete_user", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.delete_userRequestBody Body;
        
        public delete_userRequest() {
        }
        
        public delete_userRequest(bloodpressure_tracking.user_Data.delete_userRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class delete_userRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public delete_userRequestBody() {
        }
        
        public delete_userRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class delete_userResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="delete_userResponse", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.delete_userResponseBody Body;
        
        public delete_userResponse() {
        }
        
        public delete_userResponse(bloodpressure_tracking.user_Data.delete_userResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class delete_userResponseBody {
        
        public delete_userResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_idRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_id", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.get_idRequestBody Body;
        
        public get_idRequest() {
        }
        
        public get_idRequest(bloodpressure_tracking.user_Data.get_idRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_idRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        public get_idRequestBody() {
        }
        
        public get_idRequestBody(string email) {
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class get_idResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="get_idResponse", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.get_idResponseBody Body;
        
        public get_idResponse() {
        }
        
        public get_idResponse(bloodpressure_tracking.user_Data.get_idResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class get_idResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int get_idResult;
        
        public get_idResponseBody() {
        }
        
        public get_idResponseBody(int get_idResult) {
            this.get_idResult = get_idResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(bloodpressure_tracking.user_Data.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(bloodpressure_tracking.user_Data.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoringPressureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoringPressure", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.StoringPressureRequestBody Body;
        
        public StoringPressureRequest() {
        }
        
        public StoringPressureRequest(bloodpressure_tracking.user_Data.StoringPressureRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class StoringPressureRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int sys;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int dia;
        
        public StoringPressureRequestBody() {
        }
        
        public StoringPressureRequestBody(string email, int sys, int dia) {
            this.email = email;
            this.sys = sys;
            this.dia = dia;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class StoringPressureResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="StoringPressureResponse", Namespace="http://tempuri.org/", Order=0)]
        public bloodpressure_tracking.user_Data.StoringPressureResponseBody Body;
        
        public StoringPressureResponse() {
        }
        
        public StoringPressureResponse(bloodpressure_tracking.user_Data.StoringPressureResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class StoringPressureResponseBody {
        
        public StoringPressureResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface userSoapChannel : bloodpressure_tracking.user_Data.userSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class userSoapClient : System.ServiceModel.ClientBase<bloodpressure_tracking.user_Data.userSoap>, bloodpressure_tracking.user_Data.userSoap {
        
        public userSoapClient() {
        }
        
        public userSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public userSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public userSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public userSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bloodpressure_tracking.user_Data.RegisterResponse bloodpressure_tracking.user_Data.userSoap.Register(bloodpressure_tracking.user_Data.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public int Register(string fname, int age, char gender, float w, float h, string email, string password) {
            bloodpressure_tracking.user_Data.RegisterRequest inValue = new bloodpressure_tracking.user_Data.RegisterRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.RegisterRequestBody();
            inValue.Body.fname = fname;
            inValue.Body.age = age;
            inValue.Body.gender = gender;
            inValue.Body.w = w;
            inValue.Body.h = h;
            inValue.Body.email = email;
            inValue.Body.password = password;
            bloodpressure_tracking.user_Data.RegisterResponse retVal = ((bloodpressure_tracking.user_Data.userSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.RegisterResponse> bloodpressure_tracking.user_Data.userSoap.RegisterAsync(bloodpressure_tracking.user_Data.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.RegisterResponse> RegisterAsync(string fname, int age, char gender, float w, float h, string email, string password) {
            bloodpressure_tracking.user_Data.RegisterRequest inValue = new bloodpressure_tracking.user_Data.RegisterRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.RegisterRequestBody();
            inValue.Body.fname = fname;
            inValue.Body.age = age;
            inValue.Body.gender = gender;
            inValue.Body.w = w;
            inValue.Body.h = h;
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((bloodpressure_tracking.user_Data.userSoap)(this)).RegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bloodpressure_tracking.user_Data.get_infoResponse bloodpressure_tracking.user_Data.userSoap.get_info(bloodpressure_tracking.user_Data.get_infoRequest request) {
            return base.Channel.get_info(request);
        }
        
        public bloodpressure_tracking.user_Data.ArrayOfUserData get_info(string email) {
            bloodpressure_tracking.user_Data.get_infoRequest inValue = new bloodpressure_tracking.user_Data.get_infoRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.get_infoRequestBody();
            inValue.Body.email = email;
            bloodpressure_tracking.user_Data.get_infoResponse retVal = ((bloodpressure_tracking.user_Data.userSoap)(this)).get_info(inValue);
            return retVal.Body.get_infoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.get_infoResponse> bloodpressure_tracking.user_Data.userSoap.get_infoAsync(bloodpressure_tracking.user_Data.get_infoRequest request) {
            return base.Channel.get_infoAsync(request);
        }
        
        public System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.get_infoResponse> get_infoAsync(string email) {
            bloodpressure_tracking.user_Data.get_infoRequest inValue = new bloodpressure_tracking.user_Data.get_infoRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.get_infoRequestBody();
            inValue.Body.email = email;
            return ((bloodpressure_tracking.user_Data.userSoap)(this)).get_infoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bloodpressure_tracking.user_Data.updateResponse bloodpressure_tracking.user_Data.userSoap.update(bloodpressure_tracking.user_Data.updateRequest request) {
            return base.Channel.update(request);
        }
        
        public void update(string email, string fname, int age, char gender, float w, float h, string password) {
            bloodpressure_tracking.user_Data.updateRequest inValue = new bloodpressure_tracking.user_Data.updateRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.updateRequestBody();
            inValue.Body.email = email;
            inValue.Body.fname = fname;
            inValue.Body.age = age;
            inValue.Body.gender = gender;
            inValue.Body.w = w;
            inValue.Body.h = h;
            inValue.Body.password = password;
            bloodpressure_tracking.user_Data.updateResponse retVal = ((bloodpressure_tracking.user_Data.userSoap)(this)).update(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.updateResponse> bloodpressure_tracking.user_Data.userSoap.updateAsync(bloodpressure_tracking.user_Data.updateRequest request) {
            return base.Channel.updateAsync(request);
        }
        
        public System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.updateResponse> updateAsync(string email, string fname, int age, char gender, float w, float h, string password) {
            bloodpressure_tracking.user_Data.updateRequest inValue = new bloodpressure_tracking.user_Data.updateRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.updateRequestBody();
            inValue.Body.email = email;
            inValue.Body.fname = fname;
            inValue.Body.age = age;
            inValue.Body.gender = gender;
            inValue.Body.w = w;
            inValue.Body.h = h;
            inValue.Body.password = password;
            return ((bloodpressure_tracking.user_Data.userSoap)(this)).updateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bloodpressure_tracking.user_Data.delete_readingsResponse bloodpressure_tracking.user_Data.userSoap.delete_readings(bloodpressure_tracking.user_Data.delete_readingsRequest request) {
            return base.Channel.delete_readings(request);
        }
        
        public void delete_readings(string email) {
            bloodpressure_tracking.user_Data.delete_readingsRequest inValue = new bloodpressure_tracking.user_Data.delete_readingsRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.delete_readingsRequestBody();
            inValue.Body.email = email;
            bloodpressure_tracking.user_Data.delete_readingsResponse retVal = ((bloodpressure_tracking.user_Data.userSoap)(this)).delete_readings(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.delete_readingsResponse> bloodpressure_tracking.user_Data.userSoap.delete_readingsAsync(bloodpressure_tracking.user_Data.delete_readingsRequest request) {
            return base.Channel.delete_readingsAsync(request);
        }
        
        public System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.delete_readingsResponse> delete_readingsAsync(string email) {
            bloodpressure_tracking.user_Data.delete_readingsRequest inValue = new bloodpressure_tracking.user_Data.delete_readingsRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.delete_readingsRequestBody();
            inValue.Body.email = email;
            return ((bloodpressure_tracking.user_Data.userSoap)(this)).delete_readingsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bloodpressure_tracking.user_Data.delete_userResponse bloodpressure_tracking.user_Data.userSoap.delete_user(bloodpressure_tracking.user_Data.delete_userRequest request) {
            return base.Channel.delete_user(request);
        }
        
        public void delete_user(string email) {
            bloodpressure_tracking.user_Data.delete_userRequest inValue = new bloodpressure_tracking.user_Data.delete_userRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.delete_userRequestBody();
            inValue.Body.email = email;
            bloodpressure_tracking.user_Data.delete_userResponse retVal = ((bloodpressure_tracking.user_Data.userSoap)(this)).delete_user(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.delete_userResponse> bloodpressure_tracking.user_Data.userSoap.delete_userAsync(bloodpressure_tracking.user_Data.delete_userRequest request) {
            return base.Channel.delete_userAsync(request);
        }
        
        public System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.delete_userResponse> delete_userAsync(string email) {
            bloodpressure_tracking.user_Data.delete_userRequest inValue = new bloodpressure_tracking.user_Data.delete_userRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.delete_userRequestBody();
            inValue.Body.email = email;
            return ((bloodpressure_tracking.user_Data.userSoap)(this)).delete_userAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bloodpressure_tracking.user_Data.get_idResponse bloodpressure_tracking.user_Data.userSoap.get_id(bloodpressure_tracking.user_Data.get_idRequest request) {
            return base.Channel.get_id(request);
        }
        
        public int get_id(string email) {
            bloodpressure_tracking.user_Data.get_idRequest inValue = new bloodpressure_tracking.user_Data.get_idRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.get_idRequestBody();
            inValue.Body.email = email;
            bloodpressure_tracking.user_Data.get_idResponse retVal = ((bloodpressure_tracking.user_Data.userSoap)(this)).get_id(inValue);
            return retVal.Body.get_idResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.get_idResponse> bloodpressure_tracking.user_Data.userSoap.get_idAsync(bloodpressure_tracking.user_Data.get_idRequest request) {
            return base.Channel.get_idAsync(request);
        }
        
        public System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.get_idResponse> get_idAsync(string email) {
            bloodpressure_tracking.user_Data.get_idRequest inValue = new bloodpressure_tracking.user_Data.get_idRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.get_idRequestBody();
            inValue.Body.email = email;
            return ((bloodpressure_tracking.user_Data.userSoap)(this)).get_idAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bloodpressure_tracking.user_Data.loginResponse bloodpressure_tracking.user_Data.userSoap.login(bloodpressure_tracking.user_Data.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string email, string password) {
            bloodpressure_tracking.user_Data.loginRequest inValue = new bloodpressure_tracking.user_Data.loginRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.loginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            bloodpressure_tracking.user_Data.loginResponse retVal = ((bloodpressure_tracking.user_Data.userSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.loginResponse> bloodpressure_tracking.user_Data.userSoap.loginAsync(bloodpressure_tracking.user_Data.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.loginResponse> loginAsync(string email, string password) {
            bloodpressure_tracking.user_Data.loginRequest inValue = new bloodpressure_tracking.user_Data.loginRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.loginRequestBody();
            inValue.Body.email = email;
            inValue.Body.password = password;
            return ((bloodpressure_tracking.user_Data.userSoap)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        bloodpressure_tracking.user_Data.StoringPressureResponse bloodpressure_tracking.user_Data.userSoap.StoringPressure(bloodpressure_tracking.user_Data.StoringPressureRequest request) {
            return base.Channel.StoringPressure(request);
        }
        
        public void StoringPressure(string email, int sys, int dia) {
            bloodpressure_tracking.user_Data.StoringPressureRequest inValue = new bloodpressure_tracking.user_Data.StoringPressureRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.StoringPressureRequestBody();
            inValue.Body.email = email;
            inValue.Body.sys = sys;
            inValue.Body.dia = dia;
            bloodpressure_tracking.user_Data.StoringPressureResponse retVal = ((bloodpressure_tracking.user_Data.userSoap)(this)).StoringPressure(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.StoringPressureResponse> bloodpressure_tracking.user_Data.userSoap.StoringPressureAsync(bloodpressure_tracking.user_Data.StoringPressureRequest request) {
            return base.Channel.StoringPressureAsync(request);
        }
        
        public System.Threading.Tasks.Task<bloodpressure_tracking.user_Data.StoringPressureResponse> StoringPressureAsync(string email, int sys, int dia) {
            bloodpressure_tracking.user_Data.StoringPressureRequest inValue = new bloodpressure_tracking.user_Data.StoringPressureRequest();
            inValue.Body = new bloodpressure_tracking.user_Data.StoringPressureRequestBody();
            inValue.Body.email = email;
            inValue.Body.sys = sys;
            inValue.Body.dia = dia;
            return ((bloodpressure_tracking.user_Data.userSoap)(this)).StoringPressureAsync(inValue);
        }
    }
}
